env:
  global:
    secure: "kNIrwu9xazVClE1GsKz3zMMauQlBxQT5uwP7pBHiZ0/Ukz6dTvZCxSP67hVZxc8tnKPbyM1KiPKnpMd7tIJPTNbv+fS/Q7Ji9hxDe66JDgbW1Qszm5B2MBWY1n4n0hVugbYmQBqti/YXWsEq24DBYZMumSske7kKv5Gv99MA2Bz5iEvGewuxYy0TwVpaYxmDSUYjN0Hgx1oHD91JWQc/7+tA40GQORF0sA3yNvCobcSXwzWYIi6a61QhhDy8EjOphmYXjlViNrv0UWrd0BJyohotIZfWz84I+nHROJVWeG4zOWlOvc4z4Wwot4Wzl87rII77gxoX8tUxXSRUK0B1m+nZl/sL0nawAx+ABjLmr9SrOLik4izZJiz0HDosq0HpqoXSXgS6dsCuyPjzoh90BSNfYmJmArcujfGuoJclH0lEGm5Uf6sSFRR0BhJjIkJsoAdow4SYAW/0oZpCxOdVs0tK3+YLRA7281WZSKMJ/sg9NP1Pbdk1wvXSOibAN/x4eBy2Ff0VadQovHIuSg42Yqozty+8mMie4TMiNru9ZFSNmmFTslP55n3Fo/6Mv/QXzFVd7PWaWIZzYEfT3M3PPBjXCp6XQDXl2qig+SYn8MRfbWKJAZaDkGjgDeQx+5kujhfwpPJO0trzgmF20ScopWRrwatheo746I0crKBja9Q="
notifications:
  email: false
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never

sudo: false

os:
- osx
- linux

language: node_js

node_js:
- 8

addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then 
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi

install:
- npm upgrade
- npm install
- npm install -g mocha
- npm run vscode:prepublish

script:
- npm test

before_deploy:
- npm install -g json;
- npm install -g vsce;
- vsce package;
- thetag="v$(cat package.json | json version)"
- git tag $thetag || true

deploy:
- provider: releases
  api_key:
    secure: ilhwOXgAnQicNr32TCYZjvM5CSorpZbqdmPCh38Kl3DBWouYGVQ8XGsJ1d+64g8/AWqbLSeuNDutuXi06UZSRncQZeF4v7y8XcHMaSaI/CrclLwTcJk1STh3qrm1hyfG915X/mpA9nJnowQtkciktB/u38ZljNKPV2U+B9YMGk0DaBxyaiZnyJQQZ524DzLxGzYiZ8hoBZuVE717gF47E/wKdZUvyFpd5y3HCYhmAQGXjEKT3QnxervLlTdCX1FPQzCpxKja9NpH2hdnBnX0t7Ij8URqL843S7B3UiQYH3/Sfz+Pv3KLxQ0jO+OhNLeVjWx2kgZOK10w/AWhuwJK83Su68M9fSKf3Rec5tvQAKEtWxOz6Rvd1MLOgwFwpP2HFvgnM2HzEZ1yx31xSoHEx9QsKij7qbNZnYgE78ALXlFhroMymzKXQ1DnnaBWcuADB+3l2vwIc7jb8Cgg09KcBVKyl1XOriXRO9TYc6Y4up0ySlGtZ3s0xKGTHO3Tla/1U7OdIj942NODanzaw7PhXGTZNT9TMMLm6vHGMXiIZtXdW5tVEjb97N7lRR5TCgzat/6PiVnwnHUrESAcE1gT357BhM1BaIQh8lyYmGfr/DbuKp0my4VKHT+2XhAW6JpMTBFSSbEM5QInv6FFQ4Khipl6E99cN9UTsnni5KQYkRA=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: AmpersandTarski/Ampersand-Language-Support
    branch: master
    condition: $TRAVIS_OS_NAME = linux
    tag: true
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on: 
    repo: AmpersandTarski/Ampersand-Language-Support
    branch: master
    condition: $TRAVIS_OS_NAME = linux
    tag: true
