name: 'Bump Version'

on:
  workflow_call:

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: 12
      - name: 'update git'
        run: |
           git remote update
           git fetch
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
             # See https://github.com/phips28/gh-action-bump-version#readme for details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v'
          target-branch: 'master'
          minor-wording:  'add,Adds,new'
          major-wording:  'MAJOR,cut-major'
          patch-wording:  'patch,fixes' 
              # Providing patch-wording will override commits
              # defaulting to a patch bump.
          rc-wording:     'RELEASE,alpha'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          push: true
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"