on:
  workflow_call:
      
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: install vsce
        run: npm i -g @vscode/vsce

      - name: set git variables
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: git add
        run: git add .

      - name: git commit
        run: git commit -m "cleanup branch"

      - name: git status
        run: git status

      - name: publish vsce
        run: "vsce publish patch -p $VSCE_TOKEN -m 'CI: bumps version to %s'"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: git push
        run: git push -u ${{ github.ref_name }} --tags